apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-newapp-front
spec:
  selector:
    matchLabels:
      run: my-newapp-front
  replicas: 2
  template:
    metadata:
      labels:
        run: my-newapp-front
    spec:
      containers:
      - name: my-newapp-front
        image: gcr.io/prj-diameterhealth-working/divakar/front-image:v1
        ports:
        - containerPort: 80